name: Builder-DotNet
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: |
          set -euo pipefail
          pushd "${{ inputs.pipeline }}" >/dev/null
          dotnet restore
          dotnet build -c Release
          dotnet test -c Release --no-build || true
          popd >/dev/null