#HM trigger="mise.toml" workflow=".github/workflows/builder-mise.yml"
name: Builder-Mise
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
      runner:
        required: false
      env:
        required: false
      task:
        required: false
jobs:
  build:
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Import env
        run: |
          echo '${{ inputs.env }}' | jq -r 'to_entries[]|"\(.key)=\(.value)"' >> "$GITHUB_ENV"
      - run: |
          set -euo pipefail
          task="${{ inputs.task }}"
          if [[ -n "$task" ]]; then
            mise run -C "${{ inputs.pipeline }}" "$task"
          else
            mise run -C "${{ inputs.pipeline }}" build
          fi