#HM trigger=".csproj|global.json|NuGet.config"
name: Builder-DotNet
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
      runner:
        required: false
      env:
        required: false
jobs:
  build:
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Import env
        run: |
          echo '${{ inputs.env }}' | jq -r 'to_entries[]|"\(.key)=\(.value)"' >> "$GITHUB_ENV"
      - name: dotnet restore
        run: |
          set -euo pipefail
          pushd "${{ inputs.pipeline }}" >/dev/null
          dotnet restore
          popd >/dev/null
      - name: dotnet build
        run: |
          set -euo pipefail
          pushd "${{ inputs.pipeline }}" >/dev/null
          dotnet build -c Release
          popd >/dev/null
      - name: dotnet test
        run: |
          set -euo pipefail
          pushd "${{ inputs.pipeline }}" >/dev/null
          dotnet test -c Release --no-build || true
          popd >/dev/null