name: Builder-Configure-Make
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
      runner:
        required: false
jobs:
  build:
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: |
          set -euo pipefail
          pushd "${{ inputs.pipeline }}" >/dev/null
          chmod +x ./configure || true
          ./configure
          make -j"$(nproc)"
          popd >/dev/null