name: Builder-Node
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
      runner:
        required: false
      env:
        required: false
jobs:
  build:
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Import env
        run: |
          echo '${{ inputs.env }}' | jq -r 'to_entries[]|"\(.key)=\(.value)"' >> "$GITHUB_ENV"
      - run: |
          set -euo pipefail
          npm --prefix "${{ inputs.pipeline }}" ci
          npm --prefix "${{ inputs.pipeline }}" run build --if-present