name: Builder-Node
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: |
          set -euo pipefail
          npm --prefix "${{ inputs.pipeline }}" ci
          npm --prefix "${{ inputs.pipeline }}" run build --if-present