name: Builder-Buildah
on:
  workflow_dispatch:
    inputs:
      pipeline:
        required: true
      ref:
        required: true
      runner:
        required: false
jobs:
  build:
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - run: |
          set -euo pipefail
          PIPELINE="${{ inputs.pipeline }}"
          IMAGE_TAG="${IMAGE_TAG:-${GITHUB_REF_NAME}}"
          REGISTRY="${REGISTRY:-}"
          IMAGE_PATH="${IMAGE_PATH:-$(basename "$(dirname "$PIPELINE")")/$(basename "$PIPELINE")}"
          ref="${REGISTRY:+$REGISTRY/}${IMAGE_PATH}:$IMAGE_TAG"
          buildah bud -t "$ref" -f "$PIPELINE/Containerfile" "$PIPELINE"
          echo "IMAGE_REF=$ref" >> "$GITHUB_OUTPUT"