### Schedule
# This workflow is schedules the lighthouse keeper to be run every 20 min
on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'

jobs:
  run-lighthouse-keeper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cache for mise
        id: cache-mise
        uses: actions/cache@v3
        with:
          path: ~/.local/share/mise
          key: ${{ runner.os }}-mise
          restore-keys:
            ${{ runner.os }}-mise-

      - name: Install mise
        if: steps.cache-mise.outputs.cache-hit != 'true'
        run: curl -fsSL https://mise.jdx.gg/install.sh | sh && echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        shell: bash


      - name: Set up cache for nickel
        id: cache-nickel
        uses: actions/cache@v3
        with:
          path: ~/.local/share/mise/bin/nickel
          key: ${{ runner.os }}-nickel
          restore-keys:
            ${{ runner.os }}-nickel-
      - name: install nickel
        if: steps.cache-nickel.outputs.cache-hit != 'true'
        run: | 
          mise tools install
          mise tools use -g

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Lighthouse Keeper
        run: |
          cd /home/keith/devops-cove/the-github-taverns/the-lighthouse-inn/
          ./lighthouse.sh