#!/bin/bash

### Schedule
# This workflow schedules the lighthouse to scan the horizon for changes
# Run every 20 minutes

on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'

jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run test Lighthouse
        shell: bash
        run: |
          cd /home/keith/devops-cove/the-github-taverns/the-lighthouse-inn
          chmod +x ./test-lighthouse.sh
          ./test-lighthouse.sh

