name: Harbour-Master

on:
  workflow_call:
    inputs:
      pipeline:
        required: false
        type: string
      ref:
        required: true
        type: string
      tech:
        required: true
        type: string
      env_json:
        required: false
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Import env
        env:
          env_json: ${{ inputs.env_json }}
        run: |
          echo "$env_json" | jq -r 'to_entries[]|"\(.key)=\(.value)"' >> "$GITHUB_ENV"

      - name: Verify hooks (${{ inputs.tech }})
        run: |
          set -euo pipefail
          # run each executable file in verify hooks (global and ${TECH}-specific)
          find .github/hooks/verify.d .github/hooks/${{ inputs.tech }}/verify.d -type f -perm -u+x -execdir sh -c '"$0"' {} \; 2>/dev/null

      - name: Pre-publish hooks (${{ inputs.tech }})
        run: |
          set -euo pipefail
          # run each executable file in pre-publish hooks (global and ${TECH}-specific)
          find .github/hooks/pre-publish.d .github/hooks/${{ inputs.tech }}/pre-publish.d -type f -perm -u+x -execdir sh -c '"$0"' {} \; 2>/dev/null

      - name: Publish hooks (${{ inputs.tech }})
        run: |
          set -euo pipefail
          # run each executable file in publish hooks (global and ${TECH}-specific)
          find .github/hooks/publish.d .github/hooks/${{ inputs.tech }}/publish.d -type f -perm -u+x -execdir sh -c '"$0"' {} \; 2>/dev/null

      - name: Post-publish hooks (${{ inputs.tech }})
        run: |
          set -euo pipefail
          # run each executable file in post-publish hooks (global and ${TECH}-specific)
          find .github/hooks/post-publish.d .github/hooks/${{ inputs.tech }}/post-publish.d -type f -perm -u+x -execdir sh -c '"$0"' {} \; 2>/dev/null

      - name: Report hooks (${{ inputs.tech }})
        run: |
          set -euo pipefail
          # run each executable file in report hooks (global and ${TECH}-specific)
          find .github/hooks/report.d .github/hooks/${{ inputs.tech }}/report.d -type f -perm -u+x -execdir sh -c '"$0"' {} \; 2>/dev/null
